content:
  source:
    alias: configmap-reload
    dockerfile: Dockerfile
    path: ''
from:
  member: openshift-enterprise-base
labels:
  License: GPLv2+
  io.k8s.description: This is a component reloads another process if a configured
    configmap volume is remounted.
  io.k8s.display-name: configmap reload
  io.openshift.tags: kubernetes
  vendor: Red Hat
name: openshift3/ose-configmap-reloader
owners:
- fbranczy@redhat.com
