content:
  source:
    alias: prometheus-operator
    dockerfile: Dockerfile.config-reloader
from:
  member: openshift-enterprise-base
labels:
  License: GPLv2+
  io.k8s.description: This component reloads a Prometheus server in a controlled and
    configurable way.
  io.k8s.display-name: Prometheus config reloader
  io.openshift.tags: prometheus
  vendor: Red Hat
name: openshift3/ose-prometheus-config-reloader
owners:
- fbranczy@redhat.com
