content:
  source:
    alias: prometheus
    specfile: golang-github-prometheus-prometheus.spec
name: golang-github-prometheus-prometheus
owners:
- kgeorgie@redhat.com
- pgier@redhat.com
- spasquie@redhat.com